feat: реализовать вэб приложение с базовыми инструментами Spring (Спр…
DanSBol/java-filmorate pull request #1
Opened 2024-02-08 18:16 UTC by DanSBol

…инт 9)

- реализовать REST API (GET, POST, PUT)
- добавить валидацию аннотацией
- добавить логирование и тестирование

2024-02-09 09:58 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2024-02-09 09:58 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/annotations/ExceptedSymbols.java
> +@Retention(RetentionPolicy.RUNTIME)
круто что свою аннотацию сделали! Это даже некоторых миддлов иногда сложно)

2024-02-09 09:58 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/annotations/ExceptedSymbols.java
> +public @interface ExceptedSymbols {
давайте только в InvalidSymbols переименуем

2024-02-09 09:58 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/annotations/ExceptedSymbolsValidator.java
> +public class ExceptedSymbolsValidator implements ConstraintValidator<ExceptedSymbols, String> {
InvalidSymbolsValidator

2024-02-09 09:58 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    void validate(Film film) throws ValidationException {
удалите ненужный метод

2024-02-09 09:58 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final List<Film> films = new ArrayList<>();
так не пойдет, храните в Map<Integer, Film> films = new HashMap<>();

2024-02-09 09:58 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        for (Film item : films) {
когда поправите коммент выше, то здесь будет
Film filmToUpdate = films.get(film.getId());
...
только проверяйте чтобы можно было обновлять только фильмы, которые у вас есть в мае

2024-02-09 09:58 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return films;
а здесь будет return films.values()

2024-02-09 09:58 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final List<User> users = new ArrayList<>();
смотрите комменты в FilmController

2024-02-09 18:58 UTC, DanSBol commented on src/main/java/ru/yandex/practicum/filmorate/annotations/ExceptedSymbols.java
> +public @interface ExceptedSymbols {
ok

2024-02-09 18:58 UTC, DanSBol commented on src/main/java/ru/yandex/practicum/filmorate/annotations/ExceptedSymbolsValidator.java
> +public class ExceptedSymbolsValidator implements ConstraintValidator<ExceptedSymbols, String> {
ok

2024-02-09 19:01 UTC, DanSBol commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    void validate(Film film) throws ValidationException {
Метод используется классом FilmControllerTest (корневая папка test). По ТЗ нужны тесты. При повторном замечании об удалении прошу комментарий - как быть с тестами

2024-02-09 19:03 UTC, DanSBol commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final List<Film> films = new ArrayList<>();
ok

2024-02-09 19:15 UTC, DanSBol commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        for (Film item : films) {
Выполнил. Но я поправил содержимое Map через перебор Map.Entry<Integer, Film> в мапе films и метод setValue(film)

2024-02-09 19:17 UTC, DanSBol commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return films;
ok

2024-02-09 19:19 UTC, DanSBol commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final List<User> users = new ArrayList<>();
ok

2024-02-10 05:22 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2024-02-10 05:22 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        for (Map.Entry<Integer, Film> entry : films.entrySet()) {
зачем?) вы же проходили Map.
вот так сделайте
```
if (films.contains(film.getId()) {
   films.put(film.getId(), film)
   return film;
}
throw new ResponseStatusException(HttpStatus.NOT_FOUND, "HTTP Status will be BAD REQUEST (CODE 400)\n");
```

2024-02-10 05:22 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User update(@Valid @RequestBody User user) {
смотрите коммент в FilmController

2024-02-10 05:22 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @Pattern (regexp = "^\\S+$", message = "User login invalid")
отлично

2024-02-10 05:22 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    void validate(Film film) throws ValidationException {
хорошо, вы правы, оставляйте так.
Но по идее, надо тестировать контроллер, то есть имитировать вызов вашего эндпойнта.

2024-02-10 13:58 UTC, ErkinKasymaliev approved these changes
работа принята, только перед мержем коммент поправьте

2024-02-10 13:58 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        user.setId(++id);
усложняете, вот так давайте:
```
@PostMapping
public User create(@Valid @RequestBody User user) {
     log.info("Creating user {}", user);
     user.setId(++id);
     if (user.getName() == null || user.getName().isEmpty()) {
            user.setName(uset.getLogin());
     }
     users.put(user.getId(), user);
     return user;
}
```

2024-02-12 11:56 UTC, DanSBol commented
feat: содать заготовку web приложения filmorate (Спринт 9)
- реализовать REST API (GET, POST, PUT)
- добавить валидацию аннотацией
- добавить логирование и тестирование

2024-02-12 11:56 UTC, merged