feat: переработать архитектуру приложения filmorate (Спринт 10)
DanSBol/java-filmorate pull request #2
Opened 2024-02-17 14:20 UTC by DanSBol

- бизнес логику перенести в пакет service (классы UserService и FilmService)
- работу с хранилищем перенести в пакет storage (классы InMemoryUserStorage и InMemoryFilmStorage)
- добавить функционал про список друзей и лайки

2024-02-17 18:21 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2024-02-17 18:21 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>  public class Film {
а зачем убрали аннотации?

2024-02-17 18:21 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>  public class User {
а зачем убрали аннотации?

2024-02-17 18:21 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService) {
уберите конструктор и добавьте над классом аннотацию @RequiredArgsConstructor

2024-02-17 18:21 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public UserController(UserService userService) {
уберите конструктор и добавьте над классом аннотацию @RequiredArgsConstructor

2024-02-17 18:21 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    @Autowired
уберите конструктор и добавьте над классом аннотацию @RequiredArgsConstructor

2024-02-17 18:21 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    @Autowired
уберите конструктор и добавьте над классом аннотацию @RequiredArgsConstructor

2024-02-17 18:21 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Optional<Film> optionalFilm = inMemoryFilmStorage.get(id);
тут можно элегантнее сделать:
```
return inMemoryFilmStorage.get(id)
                  .orElseThrow(() -> throw new NotFoundException("Film not found."));
```
можно поправить и в других классах и методах

2024-02-17 18:21 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    @Getter
зачем геттер и сеттеры?

2024-02-17 18:21 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        this.id = 0;
можно сразу на 18 строке проинициализировать 
private int id = 0;

2024-02-17 18:21 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        if (films.containsKey(id)) {
```
Film film = films.get(id);
return film != null ? Optional.of(film) : Optional.empty();

```

можно и в других методах, классах поправить

2024-02-17 18:21 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    @Setter
смотрите комменты в InMemoryFilmStorage

2024-02-19 16:55 UTC, DanSBol commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>  public class Film {
Тесты не отрабатывали с валидацией аннотациями. Разобрался. Поправил.

2024-02-19 16:55 UTC, DanSBol commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>  public class User {
Поправил.

2024-02-19 16:56 UTC, DanSBol commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService) {
Упустил. Было это в спринте. Спс

2024-02-19 16:56 UTC, DanSBol commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public UserController(UserService userService) {
Поправил

2024-02-19 16:56 UTC, DanSBol commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    @Autowired
Поправил

2024-02-19 16:57 UTC, DanSBol commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Optional<Film> optionalFilm = inMemoryFilmStorage.get(id);
Спасибо. Лямбда тихим ужасом мимо прошли и быстро вышли...

2024-02-19 16:57 UTC, DanSBol commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +    @Getter
Поправил. Забыл убрать. Спс

2024-02-19 16:57 UTC, DanSBol commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        this.id = 0;
Где-то вычитал, что инициализация вне конструктора - плохой тон. Поправил

2024-02-19 16:58 UTC, DanSBol commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        if (films.containsKey(id)) {
Поправил

2024-02-19 16:58 UTC, DanSBol commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +    @Setter
Поправил

2024-02-19 16:58 UTC, DanSBol commented
Замечания учел

2024-02-20 04:58 UTC, ErkinKasymaliev approved these changes
привет, работа принята!

2024-02-24 09:50 UTC, DanSBol commented
feat: переработать архитектуру приложения filmorate (Спринт 10)
- бизнес логику перенести в пакет service (классы UserService и FilmService)
- работу с хранилищем перенести в пакет storage (классы InMemoryUserStorage и InMemoryFilmStorage)
- добавить функционал про список друзей и лайки

2024-02-24 09:50 UTC, merged